language: scala
scala:
  - 2.12.10
services:
  - docker
before_script:
  - docker-compose up -d
script:
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sbt ++$TRAVIS_SCALA_VERSION it:test
#after_failure:
#  - docker-compose logs
after_script:
  - docker-compose rm -f
