language: scala
scala:
  - 2.13.1
  - 2.12.10
  - 2.11.12
services:
  - docker
before_script:
  - docker-compose up
script:
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sbt ++$TRAVIS_SCALA_VERSION it:test
