version: '3.1'
services:
  zk:
    image: zookeeper:3.5.5
    hostname: zk
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
      ZOO_STANDALONE_ENABLED: "true"

  kafka:
    image: hilios/kafka:2.3.0
    depends_on:
      - zk
    links:
      - zk
    ports:
      - 9092:9092
      - 9093:9093
    command:
      - --override
      - advertised.listeners=INTERNAL://:9093,EXTERNAL://localhost:9092
      - --override
      - listeners=INTERNAL://:9093,EXTERNAL://:9092
      - --override
      - listener.security.protocol.map=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - --override
      - inter.broker.listener.name=INTERNAL
      - --override
      - zookeeper.connect=zk:2181
      - --override
      - offsets.topic.replication.factor=1
      - --override
      - auto.create.topics.enable=true
      - --override
      - auto.leader.rebalance.enable=false
