version: '3.1'
services:
  zookeeper:
    image: zookeeper:3.5.5
    hostname: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
      ZOO_STANDALONE_ENABLED: "true"

  kafka:
    image: confluentinc/cp-kafka:5.4.1
    ports:
      - 19092:19092
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=INTERNAL://kafka:9092,OUTSIDE://kafka:19092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,OUTSIDE://localhost:19092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_LOG_FLUSH_INTERVAL_MESSAGES=5
      - KAFKA_LOG_FLUSH_INTERVAL_MS=100
      - KAFKA_LOG_FLUSH_OFFSET_CHECKPOINT_INTERVAL_MS=10
      - KAFKA_DELETE_TOPIC_ENABLE=true
