package io.kafka4s.effect.producer.config

/**
  * The compression type for all data generated by the producer. The default is none (i.e. no compression).
  * Compression is of full batches of data, so the efficacy of batching will also impact the compression ratio (more
  * batching means better compression).
  *
  * @see [[org.apache.kafka.clients.producer.ProducerConfig.COMPRESSION_TYPE_DOC]]
  */
sealed abstract class CompressionType private (val value: String) { self =>
  def unapply(value: String): Option[self.type] = if (value == self.value) Some(self) else None
}

object CompressionType {

  final object Gzip extends CompressionType(value   = "gzip")
  final object Snappy extends CompressionType(value = "snappy")
  final object Lz4 extends CompressionType(value    = "lz4")
  final object Zstd extends CompressionType(value   = "zstd")
  final object None extends CompressionType(value   = "none")

  def apply(value: String): CompressionType = value match {
    case Gzip(c)   => c
    case Snappy(c) => c
    case Lz4(c)    => c
    case Zstd(c)   => c
    case None(c)   => c
  }
}
